# define version of the file to allow automatic docker swamr
version: "3.9"
# we store in a volume "like a database" declared in local with "docker volume create"
volumes:
  web_data:
    external: true
services:
  mysql:
    container_name: mysql
    restart: always
    image:  mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
    volumes: 
      - type: volume
        source: web_data
        target: /var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1