# define version of the file to allow automatic docker swamr
version: "3.9"
services:
  web:
    image: silox/alicia:master
    ports:
    - "31415:80"
    container_name: web
    restart: always
    build:
      context: ./dist
      dockerfile: ../dockerfile
    deploy:
      mode: replicated
      replicas: 6
      placement:
        max_replicas_per_node: 1
