
name: Deploy
on:
  workflow_run:
    workflows:
      - Build, docker and gh-pages
    types:
      - completed
jobs:
  post-test-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: haya14busa/action-workflow_run-status@v1
      - uses: actions/checkout@v2
      - run: exit 0
  deploy-ssh-server:
    runs-on: ubuntu-latest
    steps:
      -
        name: multiple command
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY_MACBOOK }}
          script: docker run -d silox/alicia:master