
name: Deploy
on:
  workflow_run:
    workflows:
      - Compilation
    branches:
      - main
    types:
      - completed
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
        -
          name: Publish Github Actions
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist
  deploy-ssh-server:
    runs-on: ubuntu-latest
    steps:
      -
        name: multiple command
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY_MACBOOK }}
          script: docker run -d silox/alicia:latest