name: Build, docker and gh-pages
on:
  push:
    branches: master
jobs:
  typescript-compilation:
    runs-on: ubuntu-latest
    steps:
      -
          name: Checkout
          uses: actions/checkout@v2
      -
          name: Compile Typescript
          run: npm run build && ls ./dist
      - uses: actions/upload-artifact@v2
        with:
          name: build-files
          path: ./dist
  docker-image:
    runs-on: ubuntu-latest
    needs: typescript-compilation
    steps:
      -
          name: Checkout
          uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build-files
          path: ./dist
      -
          name: Set up Docker meta for naming
          id: docker_meta
          uses: crazy-max/ghaction-docker-meta@v1
          with:
            # list of Docker images to use as BASE NAME for tags like a template
            images: |
              silox/alicia
              ghcr.io/alonbalbuena/alicia
            # add git short SHA as Docker tag
            tag-sha: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  github-pages:
    runs-on: ubuntu-latest
    needs: typescript-compilation
    steps:
        -
          name: Checkout
          uses: actions/checkout@v2
        -
          uses: actions/download-artifact@v2
          with:
            name: build-files
            path: ./dist
        -
          name: Publish Github Actions
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist
