name: compilation
on:
  push:
    branches: master
jobs:
  typescript-compilation:
    runs-on: ubuntu-latest
    steps:
      -
          name: Checkout
          uses: actions/checkout@v2
      -
          name: Compile Typescript
          run: npm run build
